# Generated by Django 5.2.7 on 2026-06-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(help_text='The ID from the fintech app', max_length=255, unique=True)),
                ('risk_score', models.IntegerField(default=0, help_text='Calculated score from 0 10 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique hardware ID from flutter', max_length=255, unique=True)),
                ('os_name', models.CharField(help_text='IOS or Android', max_length=50)),
                ('os_version', models.CharField(max_length=20)),
                ('device_model', models.CharField(help_text='e.g. iPhone 15, Pixel 8', max_length=100)),
                ('is_rooted_or_jailbroken', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='system_admin.frauduser')),
            ],
        ),
        migrations.CreateModel(
            name='AppEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'User Login'), ('TRANSFER', 'Money Transfer'), ('PROFILE_UPDATE', 'Profile Update'), ('SUSPICIOUS_BEHAVIOR', 'Suspicious Behavior')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable detail for admin timeline')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10)),
                ('paste_detected', models.BooleanField(default=True, help_text='True if they pasted the text instead of typing')),
                ('typing_speed_cps', models.FloatField(blank=True, help_text='Characters per second', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.devicefingerprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='system_admin.frauduser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
