# Generated by Django 5.2.7 on 2026-06-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FraudUser',
            new_name='FraudDetectionEngineUser',
        ),
        migrations.RenameModel(
            old_name='AppEvent',
            new_name='FraudDetectionTimelineEvent',
        ),
    ]
