# Generated by Django 5.2.7 on 2026-06-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0002_rename_frauduser_frauddetectionengineuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FraudDetectionTimelineEvent',
            new_name='FraudDetectionSDKTimelineEvent',
        ),
        migrations.RenameModel(
            old_name='FraudDetectionEngineUser',
            new_name='FraudDetectionSDKUser',
        ),
    ]
