# Generated by Django 5.2.7 on 2026-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcode',
            name='hashed_codes',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
    ]
