# Generated by Django 5.2.7 on 2026-03-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mga_enabled',
            new_name='mfa_enabled',
        ),
    ]
