# Generated by Django 5.2.7 on 2026-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mga_enabled_profile_mfa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
