# Generated by Django 5.2.7 on 2026-04-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_configured',
            field=models.BooleanField(default=False),
        ),
    ]
