# Generated by Django 5.2.7 on 2026-04-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_mfa_configured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_card', models.CharField(max_length=20)),
                ('card_hash', models.CharField(db_index=True, max_length=64)),
                ('expiry_date', models.DateField()),
                ('cardholder', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('location', models.CharField()),
                ('merchant_type', models.CharField(max_length=4)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
