# Generated by Django 5.2.7 on 2026-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_type',
            field=models.CharField(max_length=255),
        ),
    ]
